from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AbbreviationEntry:
    short_name: str
    full_name: str
    category: str
    structure_hint: str
    note: str
    replacement_smiles: str | None = None


# Replacement SMILES use [*:1] as the attachment point. LCSMILES removes the
# dummy atom and connects the rest of the fragment to the result's dummy atom.
ABBREVIATIONS: tuple[AbbreviationEntry, ...] = (
    AbbreviationEntry(
        "DMPE",
        "1,2-dimyristoyl-sn-glycero-3-phosphoethanolamine",
        "lipid / PE lipid",
        "PE headgroup with two C14:0 myristoyl chains",
        "常用于膜染料/脂质探针。替换片段默认通过乙醇胺 N 连接到原图里的 * 位点，适合 DMPE-amide 这类画法。",
        "[*:1]NCCOP(=O)(O)OCC(COC(=O)CCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCC",
    ),
    AbbreviationEntry(
        "DPPE",
        "1,2-dipalmitoyl-sn-glycero-3-phosphoethanolamine",
        "lipid / PE lipid",
        "PE headgroup with two C16:0 palmitoyl chains",
        "常用于膜定位探针。默认通过乙醇胺 N 连接。",
        "[*:1]NCCOP(=O)(O)OCC(COC(=O)CCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCC",
    ),
    AbbreviationEntry(
        "DSPE",
        "1,2-distearoyl-sn-glycero-3-phosphoethanolamine",
        "lipid / PE lipid",
        "PE headgroup with two C18:0 stearoyl chains",
        "常见于 DSPE-PEG、膜探针和纳米颗粒修饰。默认通过乙醇胺 N 连接。",
        "[*:1]NCCOP(=O)(O)OCC(COC(=O)CCCCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCCCC",
    ),
    AbbreviationEntry(
        "DOPE",
        "1,2-dioleoyl-sn-glycero-3-phosphoethanolamine",
        "lipid / PE lipid",
        "PE headgroup with two C18:1 oleoyl chains",
        "含双键，构型和画法需要人工核对。默认通过乙醇胺 N 连接。",
        "[*:1]NCCOP(=O)(O)OCC(COC(=O)CCCCCCC/C=C\\CCCCCCCC)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
    ),
    AbbreviationEntry(
        "POPE",
        "1-palmitoyl-2-oleoyl-sn-glycero-3-phosphoethanolamine",
        "lipid / PE lipid",
        "PE headgroup with C16:0 and C18:1 chains",
        "sn-1/sn-2 位置会影响完整结构；默认按 1-palmitoyl-2-oleoyl 写入。",
        "[*:1]NCCOP(=O)(O)OCC(COC(=O)CCCCCCCCCCCCCCC)OC(=O)CCCCCCC/C=C\\CCCCCCCC",
    ),
    AbbreviationEntry(
        "DOPC",
        "1,2-dioleoyl-sn-glycero-3-phosphocholine",
        "lipid / PC lipid",
        "PC headgroup with two C18:1 oleoyl chains",
        "PC 脂质通常不是通过头基 N 形成普通酰胺连接；多数情况下需要原文确认连接方式。",
    ),
    AbbreviationEntry(
        "Chol",
        "cholesterol",
        "lipid anchor",
        "cholesteryl anchor",
        "胆固醇锚定基常通过醚、酯、碳酸酯或 linker 连接，不能只凭 Chol 自动确定。",
    ),
    AbbreviationEntry(
        "PEG2",
        "diethylene glycol linker",
        "PEG linker",
        "two ethylene glycol units",
        "默认作为单端 O 连接片段；如果原图表示 PEG2-diamine、azido-PEG2 等，需要选对应条目或手动改。",
        "[*:1]OCCOCCO",
    ),
    AbbreviationEntry(
        "PEG3",
        "triethylene glycol linker",
        "PEG linker",
        "three ethylene glycol units",
        "默认作为单端 O 连接片段。",
        "[*:1]OCCOCCOCCO",
    ),
    AbbreviationEntry(
        "PEG4",
        "tetraethylene glycol linker",
        "PEG linker",
        "four ethylene glycol units",
        "默认作为单端 O 连接片段。",
        "[*:1]OCCOCCOCCOCCO",
    ),
    AbbreviationEntry(
        "PEG",
        "polyethylene glycol",
        "polymer/linker",
        "repeating -O-CH2-CH2- units",
        "PEG 必须知道重复单元数、端基和连接方式；单独 PEG 不是唯一结构。",
    ),
    AbbreviationEntry(
        "mPEG",
        "methoxy polyethylene glycol",
        "polymer/linker",
        "MeO-(CH2CH2O)n-",
        "需要知道 n 的数值或分子量，否则不能生成唯一 SMILES。",
    ),
    AbbreviationEntry(
        "NHS",
        "N-hydroxysuccinimide",
        "activated ester / leaving group",
        "NHS ester context",
        "NHS 可指游离 N-hydroxysuccinimide，也可指 NHS ester 片段；替换前必须看连接位置。",
    ),
    AbbreviationEntry(
        "Boc",
        "tert-butyloxycarbonyl",
        "protecting group",
        "tert-butoxycarbonyl protecting group",
        "常见氨基保护基。默认片段通过羰基连接到 * 位点。",
        "[*:1]C(=O)OC(C)(C)C",
    ),
    AbbreviationEntry(
        "Fmoc",
        "fluorenylmethyloxycarbonyl",
        "protecting group",
        "fluorene-CH2-O-C(=O)-",
        "常见氨基保护基。默认片段通过羰基连接到 * 位点。",
        "[*:1]C(=O)OCC1c2ccccc2-c2ccccc21",
    ),
    AbbreviationEntry(
        "TBS",
        "tert-butyldimethylsilyl",
        "protecting group",
        "t-BuMe2Si-",
        "也常写 TBDMS。默认通过 Si 连接。",
        "[*:1][Si](C)(C)C(C)(C)C",
    ),
    AbbreviationEntry(
        "TBDMS",
        "tert-butyldimethylsilyl",
        "protecting group",
        "t-BuMe2Si-",
        "与 TBS 常指同一保护基。",
        "[*:1][Si](C)(C)C(C)(C)C",
    ),
    AbbreviationEntry(
        "TMS",
        "trimethylsilyl",
        "protecting group",
        "Me3Si-",
        "默认通过 Si 连接。",
        "[*:1][Si](C)(C)C",
    ),
    AbbreviationEntry(
        "DBCO",
        "dibenzocyclooctyne",
        "click chemistry handle",
        "strained alkyne click handle",
        "常用于无铜点击反应。不同商品化 DBCO linker 差异较大，默认不自动替换。",
    ),
    AbbreviationEntry(
        "BCN",
        "bicyclononyne",
        "click chemistry handle",
        "strained alkyne click handle",
        "BCN linker 版本很多，连接方式需原文确认。",
    ),
    AbbreviationEntry(
        "Tz",
        "tetrazine",
        "click chemistry handle",
        "tetrazine click handle",
        "四嗪取代型很多，不能只凭 Tz 唯一展开。",
    ),
    AbbreviationEntry(
        "TCO",
        "trans-cyclooctene",
        "click chemistry handle",
        "strained alkene click handle",
        "TCO 有 axial/equatorial、linker 和构型差异，需人工确认。",
    ),
    AbbreviationEntry(
        "N3",
        "azide",
        "click chemistry handle",
        "azide group",
        "默认通过末端连接到 * 位点。",
        "[*:1]N=[N+]=[N-]",
    ),
    AbbreviationEntry(
        "alkyne",
        "terminal alkyne",
        "click chemistry handle",
        "ethynyl group",
        "默认把 * 替换为乙炔基。",
        "[*:1]C#C",
    ),
    AbbreviationEntry(
        "maleimide",
        "maleimide",
        "thiol reactive handle",
        "maleimide thiol-reactive group",
        "连接臂可能接在 N 上或环上，常见染料中多为 N-substituted maleimide，需核对。",
    ),
    AbbreviationEntry(
        "Biotin",
        "biotin",
        "affinity tag",
        "vitamin H tag with valeric acid side chain",
        "Biotin 本体唯一，但连接时可能是 amide、ester 或 linker，默认不自动替换。",
    ),
    AbbreviationEntry(
        "HaloTag",
        "HaloTag chloroalkane ligand",
        "live-cell tag ligand",
        "chloroalkane ligand for HaloTag",
        "常见为 chloroalkane linker，但商业染料 linker 长度不同，不能只凭 HaloTag 唯一展开。",
    ),
    AbbreviationEntry(
        "SNAP",
        "benzylguanine SNAP-tag ligand",
        "live-cell tag ligand",
        "O6-benzylguanine derivative",
        "SNAP-tag 染料通常含 BG 片段和 linker，具体结构取决于试剂。",
    ),
    AbbreviationEntry(
        "CLIP",
        "benzylcytosine CLIP-tag ligand",
        "live-cell tag ligand",
        "O2-benzylcytosine derivative",
        "CLIP-tag 染料具体 linker 取决于试剂。",
    ),
    AbbreviationEntry(
        "SiR",
        "silicon rhodamine",
        "fluorophore scaffold",
        "far-red fluorophore core",
        "SiR 是染料母核名称，不是唯一取代结构；需原图或商品结构。",
    ),
    AbbreviationEntry(
        "JF",
        "Janelia Fluor dye scaffold",
        "fluorophore scaffold",
        "rhodamine-like live-cell dye family",
        "JF549、JF646、JF635 等不是同一结构；必须知道编号和取代基。",
    ),
    AbbreviationEntry(
        "TMR",
        "tetramethylrhodamine",
        "fluorophore scaffold",
        "rhodamine fluorophore",
        "TMR 可能指 acid、NHS ester、maleimide、ligand conjugate 等，需上下文。",
    ),
    AbbreviationEntry(
        "Cy3",
        "cyanine 3 dye",
        "fluorophore scaffold",
        "cyanine dye family",
        "Cy3/Cy5 常有不同供应商 linker 和电荷形式，不应自动唯一展开。",
    ),
    AbbreviationEntry(
        "Cy5",
        "cyanine 5 dye",
        "fluorophore scaffold",
        "cyanine dye family",
        "Cy5 染料有多种磺酸化和 linker 版本，需原文结构。",
    ),
    AbbreviationEntry(
        "ATTO",
        "ATTO dye family",
        "fluorophore scaffold",
        "commercial dye family",
        "ATTO 后必须带编号，例如 ATTO 647N；不同编号结构完全不同。",
    ),
    AbbreviationEntry(
        "Alexa",
        "Alexa Fluor dye family",
        "fluorophore scaffold",
        "commercial dye family",
        "Alexa Fluor 488/568/647 等结构不同，供应商也常不公开完整结构。",
    ),
    AbbreviationEntry(
        "dmpe",
        "1,2-bis(dimethylphosphino)ethane",
        "ligand",
        "Me2P-CH2-CH2-PMe2",
        "和脂质 DMPE 重名但完全不是同一类结构。金属配合物文献里常写小写 dmpe。",
        "[*:1]P(C)(C)CCP(C)C",
    ),
)

